from pydantic import BaseModel, Field
from typing import List, Optional


class TopicCreate(BaseModel):
    """Payload to create a new macro-level mindmap."""
    topic: str = Field(..., description="The main topic of the mindmap.")
    guidelines: Optional[str] = Field(None, description="Optional guidelines or context to direct the generation.")


class TopicResponse(BaseModel):
    """Response containing root Topic information."""
    id: str = Field(..., description="Unique ID of the topic.")
    title: str = Field(..., description="Title of the topic.")
    description: str = Field(..., description="Brief description of the topic.")


class MindmapNodeSchema(BaseModel):
    """Schema representing a single node in the mindmap, compatible with database storage and frontend rendering."""
    id: str = Field(..., description="Unique ID of the node.")
    label: str = Field(..., description="Text label of the concept.")
    description: str = Field(..., description="One-sentence description of the concept.")
    content: Optional[str] = Field(None, description="Detailed markdown content generated for the node.")
    level: int = Field(..., description="Depth level of the node in the drill-down hierarchy (0 for root level).")
    parent_id: Optional[str] = Field(None, description="ID of the parent node if this node belongs to a sub-graph.")
    topic_id: str = Field(..., description="ID of the root Topic this node belongs to.")


class MindmapEdgeSchema(BaseModel):
    """Schema representing a directed relationship between two nodes in the mindmap."""
    id: str = Field(..., description="Unique ID of the edge.")
    source: str = Field(..., description="Source node ID.")
    target: str = Field(..., description="Target node ID.")
    relation: str = Field(..., description="Standardized verb/relationship type (e.g. PART_OF, DEPENDS_ON).")


class GraphResponse(BaseModel):
    """Response payload enclosing the full graph structure (nodes and edges) for frontend rendering."""
    topic: TopicResponse = Field(..., description="Topic context.")
    nodes: List[MindmapNodeSchema] = Field(..., description="List of nodes in the graph.")
    edges: List[MindmapEdgeSchema] = Field(..., description="List of edges/relationships in the graph.")


class NodeCreateContent(BaseModel):
    """Request payload for writing detailed node content."""
    instructions: Optional[str] = Field(None, description="Optional writing instructions or constraints.")


class DrillDownRequest(BaseModel):
    """Request payload to perform a sub-graph drill down from a specific node."""
    guidelines: Optional[str] = Field(None, description="Optional focus area or guidelines for the sub-graph.")


# --- Structured Output Pydantic schemas for Gemini Agent queries ---

class GeneratedNode(BaseModel):
    """Structure for a single concept generated by the Planner Agent."""
    label: str = Field(..., description="Concise noun or verb-phrase representing a disjoint sub-concept of similar importance.")
    description: str = Field(..., description="A one-sentence summary explaining this specific concept's role.")


class ConceptDecomposition(BaseModel):
    """Response format for the Planner Agent's decomposition task."""
    description: str = Field(..., description="An overall summary description of the topic being decomposed.")
    nodes: List[GeneratedNode] = Field(..., description="A list of 6 to 10 disjoint, distinct, non-overlapping concept nodes.")


class GeneratedEdge(BaseModel):
    """Structure for a single standardized relationship generated by the Homogenizer Agent."""
    source_label: str = Field(..., description="The label of the source concept.")
    target_label: str = Field(..., description="The label of the target concept.")
    relation: str = Field(..., description="A standardized uppercase verb phrase relationship (e.g. DEPENDS_ON, CONTAINS, PART_OF, INFLUENCES, EXPLAINS).")


class RelationshipExtraction(BaseModel):
    """Response format for the Homogenizer Agent's mapping task."""
    edges: List[GeneratedEdge] = Field(..., description="A list of standardized relationships connecting the concept nodes.")
